### ISSUE TITLE
It does not work to load MT5 coded files into MT4 editor

### ISSUE THREAD

**Issue by studybug** [EA31337/EA31337-Libre#17]
I tried working your code in my MT4 editor.  It does not work to load MT5 coded files into the MT4 editor.

**Comment by kenorb** [comment]
> I tried working your code in my MT4 editor. It does not work to load MT5 coded files into the MT4 editor.

What error do you get? The repository consist git submodules, so you've to clone it recursively, e.g.:

 ```
git clone --recursive https://github.com/EA31337/EA31337-Libre
```

Check [Compilation wiki page](https://github.com/EA31337/EA31337/wiki/Compilation) for examples.

**Comment by studybug** [comment]
Thanks for the response!  I am getting 102 errors and one warning when I compile the file in Meta editor for Metatrader 4.  See photo.
<img width="960" alt="error" src="https://user-images.githubusercontent.com/42164711/128252110-c7de2176-a291-4154-a7f2-28a43937b94b.PNG">

This is a similar issue of not working for the non-'Libre' file set.  The most common error:  'this' - undeclared identifier

**Comment by kenorb** [comment]
> Thanks for the response! I am getting 102 errors and one warning when I compile the file in Meta editor for Metatrader 4.

Have you opened `.mq4` file (not .mq5) then hit Compile?

**Comment by studybug** [comment]
I figured it out-- I had to put the whole datafile set in the expert advisers subfile with all my other single expert advisers.  It does not work to put it nearby in a subfolder in the MT4 file system.  The main problem was that it was not able to find the refrence when I only put the .mq4 and .mq5 in the expert adviser folder.
